### ISSUE TITLE
LibTorch版本问题

### ISSUE THREAD

**Issue by QCHighing** [sainttelant/libtorchYoloV3#1]
确定用的是LibTorch 1.6？我找不到torch/torch.h这个文件

**Comment by sainttelant** [comment]
Yes，  i  am sure it is version 1.6, because i just upgraded the libtorch version to the lastest version before creating this repo

**Comment by QCHighing** [comment]
OK, thx for your work! 
I hava found the `torch/torch.h` file in `libtorch/include/torch/csrc/api/include/torch`. But I don't know what is the difference between it and `torch/script.h`. And the path is toooooo deep.
